name: abc
on:
  push:
    branches:
      - deploy
  pull_request:
    types:
      - ready_for_review
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: /bin/false
