name: abc
on:
  #  push:
  #    branches:
  #      - deploy
  pull_request:
    types:
      - ready_for_review
      - synchronize
        #    branches:
        #      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ping www.github.com
